Script started on 2025-10-21 23:29:30-03:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="192" LINES="16"]
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[00m$ make
[?2004lmake ../../Binaries/Linux/libYggdrasilPRNG.a
make[1]: Entering directory '/home/hp17cp/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux'
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Vendor/Include/ -I../../Include/YggdrasilPRNG/ \
	-o ../../Source/YggdrasilPRNG/YggdrasilPRNG.o \
	-c ../../Source/YggdrasilPRNG/YggdrasilPRNG.cpp
[01m[K../../Source/YggdrasilPRNG/YggdrasilPRNG.cpp:[m[K In member function ‘[01m[Kvoid YggdrasilPRNG::[01;32m[Kseed[m[K(const std::string&, unsigned int)[m[K’:
[01m[K../../Source/YggdrasilPRNG/YggdrasilPRNG.cpp:9:45:[m[K [01;35m[Kwarning: [m[Kunused parameter ‘[01m[Kseed[m[K’ [[01;35m[K]8;;https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Warning-Options.html#index-Wno-unused-parameter-Wunused-parameter]8;;[m[K]
    9 | void YggdrasilPRNG::seed([01;35m[Kconst std::string& seed[m[K, unsigned int layerCount) {
      |                          [01;35m[K~~~~~~~~~~~~~~~~~~~^~~~[m[K
[01m[K../../Source/YggdrasilPRNG/YggdrasilPRNG.cpp:9:64:[m[K [01;35m[Kwarning: [m[Kunused parameter ‘[01m[KlayerCount[m[K’ [[01;35m[K]8;;https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Warning-Options.html#index-Wno-unused-parameter-Wunused-parameter]8;;[m[K]
    9 | void YggdrasilPRNG::seed(const std::string& seed, [01;35m[Kunsigned int layerCount[m[K) {
      |                                                   [01;35m[K~~~~~~~~~~~~~^~~~~~~~~~[m[K
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Vendor/Include/ -I../../Include/YggdrasilPRNG/ -o ../../Source/YggdrasilPRNG/Utilities.o \
	-c ../../Source/YggdrasilPRNG/Utilities.cpp
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Vendor/Include/ -I../../Include/YggdrasilPRNG/ -o ../../Source/YggdrasilPRNG/Node.o \
	-c ../../Source/YggdrasilPRNG/Node.cpp
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Vendor/Include/ -I../../Include/YggdrasilPRNG/ -o ../../Source/YggdrasilPRNG/LFSRNode.o \
	-c ../../Source/YggdrasilPRNG/LFSRNode.cpp
ar rcs ../../Binaries/Linux/libYggdrasilPRNG.a ../../Source/YggdrasilPRNG/YggdrasilPRNG.o \
	../../Source/YggdrasilPRNG/Utilities.o ../../Source/YggdrasilPRNG/Node.o \
	../../Source/YggdrasilPRNG/LFSRNode.o
make[1]: Leaving directory '/home/hp17cp/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux'
make ../../Binaries/Linux/YGen
make[1]: Entering directory '/home/hp17cp/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux'
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Include/ -o ../../Source/YGen/YGen.o \
	-c ../../Source/YGen/YGen.cpp
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -o ../../Binaries/Linux/YGen ../../Source/YGen/YGen.o -L../../Binaries/Linux/ -lYggdrasilPRNG -L../../Vendor/Libraries/ -lsha
make[1]: Leaving directory '/home/hp17cp/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux'
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[00m$ ./../../Binaries/Linux/YGen
[?2004l
Seeding LFSR node: "Hello World!"
Seed hash: 10000110000110000100010011010110011100000100111010000101011100111111111011000011010011011001011001111110001000001011110011111110111100111101010000100100110011110100100010111110000001001110011011011100000010001111001010111101010110001100011100101001011101000011001101110001000000010101111010101101100010010001110011000011110011110001110010011101001101001011010010010010011001001011010100010000011101010001101100011111111110011110010100110111100100110111101111000100011010110101110101101111111101001110110011001000
Configuration index 8: { 8, 7, 5, 4, 3, }
LFSR width: 8
State buffer: 10000110
Taps buffer: 10111000


Output bit 0: 0
Shifted state buffer: 01000011

Output bit 1: 1
Shifted state buffer: 00100001
Masked state buffer: 10011001

Output bit 2: 1
Shifted state buffer: 01001100
Masked state buffer: 11110100

Output bit 3: 0
Shifted state buffer: 01111010

Output bit 4: 0
Shifted state buffer: 00111101

Output bit 5: 1
Shifted state buffer: 00011110
Masked state buffer: 10100110

Output bit 6: 0
Shifted state buffer: 01010011

Output bit 7: 1
Shifted state buffer: 00101001
Masked state buffer: 10010001

Output bit 0: 1
Shifted state buffer: 01001000
Masked state buffer: 11110000

Output bit 1: 0
Shifted state buffer: 01111000

Output bit 2: 0
Shifted state buffer: 00111100

Output bit 3: 0
Shifted state buffer: 00011110

Output bit 4: 0
Shifted state buffer: 00001111

Output bit 5: 1
Shifted state buffer: 00000111
Masked state buffer: 10111111

Output bit 6: 1
Shifted state buffer: 01011111
Masked state buffer: 11100111

Output bit 7: 1
Shifted state buffer: 01110011
Masked state buffer: 11001011

Output bit 0: 1
Shifted state buffer: 01100101
Masked state buffer: 11011101

Output bit 1: 1
Shifted state buffer: 01101110
Masked state buffer: 11010110

Output bit 2: 0
Shifted state buffer: 01101011

Output bit 3: 1
Shifted state buffer: 00110101
Masked state buffer: 10001101

Output bit 4: 1
Shifted state buffer: 01000110
Masked state buffer: 11111110

Output bit 5: 0
Shifted state buffer: 01111111

Output bit 6: 1
Shifted state buffer: 00111111
Masked state buffer: 10000111

Output bit 7: 1
Shifted state buffer: 01000011
Masked state buffer: 11111011
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[00m$ make clean
[?2004lrm ../../Source/YggdrasilPRNG/*.o
rm ../../Binaries/Linux/libYggdrasilPRNG.a
rm ../../Source/YGen/*.o
rm ../../Binaries/Linux/YGen
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[00m$ [?2004l
exit

Script done on 2025-10-21 23:29:49-03:00 [COMMAND_EXIT_CODE="0"]
