Script started on 2025-10-22 12:40:15-03:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="192" LINES="16"]
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[00m$ make
[?2004lmake ../../Binaries/Linux/libYggdrasilPRNG.a
make[1]: Entering directory '/home/hp17cp/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux'
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Vendor/Include/ -I../../Include/YggdrasilPRNG/ \
	-o ../../Source/YggdrasilPRNG/YggdrasilPRNG.o \
	-c ../../Source/YggdrasilPRNG/YggdrasilPRNG.cpp
[01m[K../../Source/YggdrasilPRNG/YggdrasilPRNG.cpp:[m[K In member function ‘[01m[Kvoid YggdrasilPRNG::[01;32m[Kseed[m[K(const std::string&, unsigned int)[m[K’:
[01m[K../../Source/YggdrasilPRNG/YggdrasilPRNG.cpp:9:45:[m[K [01;35m[Kwarning: [m[Kunused parameter ‘[01m[Kseed[m[K’ [[01;35m[K]8;;https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Warning-Options.html#index-Wno-unused-parameter-Wunused-parameter]8;;[m[K]
    9 | void YggdrasilPRNG::seed([01;35m[Kconst std::string& seed[m[K, unsigned int layerCount) {
      |                          [01;35m[K~~~~~~~~~~~~~~~~~~~^~~~[m[K
[01m[K../../Source/YggdrasilPRNG/YggdrasilPRNG.cpp:9:64:[m[K [01;35m[Kwarning: [m[Kunused parameter ‘[01m[KlayerCount[m[K’ [[01;35m[K]8;;https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Warning-Options.html#index-Wno-unused-parameter-Wunused-parameter]8;;[m[K]
    9 | void YggdrasilPRNG::seed(const std::string& seed, [01;35m[Kunsigned int layerCount[m[K) {
      |                                                   [01;35m[K~~~~~~~~~~~~~^~~~~~~~~~[m[K
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Vendor/Include/ -I../../Include/YggdrasilPRNG/ -o ../../Source/YggdrasilPRNG/Utilities.o \
	-c ../../Source/YggdrasilPRNG/Utilities.cpp
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Vendor/Include/ -I../../Include/YggdrasilPRNG/ -o ../../Source/YggdrasilPRNG/Node.o \
	-c ../../Source/YggdrasilPRNG/Node.cpp
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Vendor/Include/ -I../../Include/YggdrasilPRNG/ -o ../../Source/YggdrasilPRNG/LFSRNode.o \
	-c ../../Source/YggdrasilPRNG/LFSRNode.cpp
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Vendor/Include/ -I../../Include/YggdrasilPRNG/ \
	-o ../../Source/YggdrasilPRNG/MatrixNode.o \
	-c ../../Source/YggdrasilPRNG/MatrixNode.cpp
ar rcs ../../Binaries/Linux/libYggdrasilPRNG.a ../../Source/YggdrasilPRNG/YggdrasilPRNG.o \
	../../Source/YggdrasilPRNG/Utilities.o ../../Source/YggdrasilPRNG/Node.o \
	../../Source/YggdrasilPRNG/LFSRNode.o ../../Source/YggdrasilPRNG/MatrixNode.o
make[1]: Leaving directory '/home/hp17cp/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux'
make ../../Binaries/Linux/YGen
make[1]: Entering directory '/home/hp17cp/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux'
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -I../../Include/ -o ../../Source/YGen/YGen.o \
	-c ../../Source/YGen/YGen.cpp
g++ -Wall -Wextra -pedantic -O3 -std=c++20 -o ../../Binaries/Linux/YGen ../../Source/YGen/YGen.o -L../../Binaries/Linux/ -lYggdrasilPRNG -L../../Vendor/Libraries/ -lsha
make[1]: Leaving directory '/home/hp17cp/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux'
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[00m$ ./../../Binaries/Linux/YGen
[?2004lSeed hash: 10000110000110000100010011010110011100000100111010000101011100111111111011000011010011011001011001111110001000001011110011111110111100111101010000100100110011110100100010111110000001001110011011011100000010001111001010111101010110001100011100101001011101000011001101110001000000010101111010101101100010010001110011000011110011110001110010011101001101001011010010010010011001001011010100010000011101010001101100011111111110011110010100110111100100110111101111000100011010110101110101101111111101001110110011001000
LFSR child count: 5
New populating child 0 <- 255 <- 11111111
Shift in byte 00011011, new matrix:
-1, 0, 0, 0, 0, 0, 0, 0, 
-1, 0, 0, 0, 0, 0, 0, 0, 
-1, 0, 0, 0, 0, 0, 0, 0, 
1, 0, 0, 0, 0, 0, 0, 0, 
1, 0, 0, 0, 0, 0, 0, 0, 
-1, 0, 0, 0, 0, 0, 0, 0, 
1, 0, 0, 0, 0, 0, 0, 0, 
1, 0, 0, 0, 0, 0, 0, 0, 
New populating child 1 <- 21 <- 00010101
Shift in byte 11001001, new matrix:
1, -1, 0, 0, 0, 0, 0, 0, 
1, -1, 0, 0, 0, 0, 0, 0, 
-1, -1, 0, 0, 0, 0, 0, 0, 
-1, 1, 0, 0, 0, 0, 0, 0, 
1, 1, 0, 0, 0, 0, 0, 0, 
-1, -1, 0, 0, 0, 0, 0, 0, 
-1, 1, 0, 0, 0, 0, 0, 0, 
1, 1, 0, 0, 0, 0, 0, 0, 
New populating child 0 <- 130 <- 10000010
Shift in byte 11000001, new matrix:
1, 1, -1, 0, 0, 0, 0, 0, 
1, 1, -1, 0, 0, 0, 0, 0, 
-1, -1, -1, 0, 0, 0, 0, 0, 
-1, -1, 1, 0, 0, 0, 0, 0, 
-1, 1, 1, 0, 0, 0, 0, 0, 
-1, -1, -1, 0, 0, 0, 0, 0, 
-1, -1, 1, 0, 0, 0, 0, 0, 
1, 1, 1, 0, 0, 0, 0, 0, 
New populating child 1 <- 21 <- 00010101
Shift in byte 01101000, new matrix:
-1, 1, 1, -1, 0, 0, 0, 0, 
1, 1, 1, -1, 0, 0, 0, 0, 
1, -1, -1, -1, 0, 0, 0, 0, 
-1, -1, -1, 1, 0, 0, 0, 0, 
1, -1, 1, 1, 0, 0, 0, 0, 
-1, -1, -1, -1, 0, 0, 0, 0, 
-1, -1, -1, 1, 0, 0, 0, 0, 
-1, 1, 1, 1, 0, 0, 0, 0, 
New populating child 0 <- 55 <- 00110111
Shift in byte 10100100, new matrix:
1, -1, 1, 1, -1, 0, 0, 0, 
-1, 1, 1, 1, -1, 0, 0, 0, 
1, 1, -1, -1, -1, 0, 0, 0, 
-1, -1, -1, -1, 1, 0, 0, 0, 
-1, 1, -1, 1, 1, 0, 0, 0, 
1, -1, -1, -1, -1, 0, 0, 0, 
-1, -1, -1, -1, 1, 0, 0, 0, 
-1, -1, 1, 1, 1, 0, 0, 0, 
New populating child 1 <- 201 <- 11001001
Shift in byte 10001010, new matrix:
1, 1, -1, 1, 1, -1, 0, 0, 
-1, -1, 1, 1, 1, -1, 0, 0, 
-1, 1, 1, -1, -1, -1, 0, 0, 
-1, -1, -1, -1, -1, 1, 0, 0, 
1, -1, 1, -1, 1, 1, 0, 0, 
-1, 1, -1, -1, -1, -1, 0, 0, 
1, -1, -1, -1, -1, 1, 0, 0, 
-1, -1, -1, 1, 1, 1, 0, 0, 
New populating child 1 <- 246 <- 11110110
Shift in byte 00110010, new matrix:
-1, 1, 1, -1, 1, 1, -1, 0, 
-1, -1, -1, 1, 1, 1, -1, 0, 
1, -1, 1, 1, -1, -1, -1, 0, 
1, -1, -1, -1, -1, -1, 1, 0, 
-1, 1, -1, 1, -1, 1, 1, 0, 
-1, -1, 1, -1, -1, -1, -1, 0, 
1, 1, -1, -1, -1, -1, 1, 0, 
-1, -1, -1, -1, 1, 1, 1, 0, 
New populating child 0 <- 145 <- 10010001
Shift in byte 00100101, new matrix:
-1, -1, 1, 1, -1, 1, 1, -1, 
-1, -1, -1, -1, 1, 1, 1, -1, 
1, 1, -1, 1, 1, -1, -1, -1, 
-1, 1, -1, -1, -1, -1, -1, 1, 
-1, -1, 1, -1, 1, -1, 1, 1, 
1, -1, -1, 1, -1, -1, -1, -1, 
-1, 1, 1, -1, -1, -1, -1, 1, 
1, -1, -1, -1, -1, 1, 1, 1, 
Finished seed function
Output byte 0: New populating child 0 <- 165 <- 10100101
Shift in byte 10010111, new matrix:
1, -1, -1, 1, 1, -1, 1, 1, 
-1, -1, -1, -1, -1, 1, 1, 1, 
-1, 1, 1, -1, 1, 1, -1, -1, 
1, -1, 1, -1, -1, -1, -1, -1, 
-1, -1, -1, 1, -1, 1, -1, 1, 
1, 1, -1, -1, 1, -1, -1, -1, 
1, -1, 1, 1, -1, -1, -1, -1, 
1, 1, -1, -1, -1, -1, 1, 1, 
Initial byte: 00100111
Initial bits: 0, 0, 1, 0, 0, 1, 1, 1, 
Product: 0, 2, 0, -2, 0, -4, -2, 0, 
Output bits: 0, 0, 1, 0, 0, 0, 1, 1, 
Output byte: 00100011
00100011
Output byte 1: New populating child 0 <- 30 <- 00011110
Shift in byte 01111000, new matrix:
-1, 1, -1, -1, 1, 1, -1, 1, 
1, -1, -1, -1, -1, -1, 1, 1, 
1, -1, 1, 1, -1, 1, 1, -1, 
1, 1, -1, 1, -1, -1, -1, -1, 
1, -1, -1, -1, 1, -1, 1, -1, 
-1, 1, 1, -1, -1, 1, -1, -1, 
-1, 1, -1, 1, 1, -1, -1, -1, 
-1, 1, 1, -1, -1, -1, -1, 1, 
Initial byte: 01100111
Initial bits: 0, 1, 1, 0, 0, 1, 1, 1, 
Product: 1, -1, 1, -3, -3, 1, -3, 1, 
Output bits: 0, 1, 1, 0, 0, 1, 0, 1, 
Output byte: 01100101
01100101
Output byte 2: New populating child 3 <- 18 <- 00010010
Shift in byte 11000110, new matrix:
1, -1, 1, -1, -1, 1, 1, -1, 
1, 1, -1, -1, -1, -1, -1, 1, 
-1, 1, -1, 1, 1, -1, 1, 1, 
-1, 1, 1, -1, 1, -1, -1, -1, 
-1, 1, -1, -1, -1, 1, -1, 1, 
1, -1, 1, 1, -1, -1, 1, -1, 
1, -1, 1, -1, 1, 1, -1, -1, 
-1, -1, 1, 1, -1, -1, -1, -1, 
Initial byte: 01111110
Initial bits: 0, 1, 1, 1, 1, 1, 1, 0, 
Product: 0, -4, 2, 0, -2, 0, 0, -2, 
Output bits: 0, 0, 1, 1, 1, 1, 1, 0, 
Output byte: 00111110
00111110
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[00m$ make clean
[?2004lrm ../../Source/YggdrasilPRNG/*.o
rm ../../Binaries/Linux/libYggdrasilPRNG.a
rm ../../Source/YGen/*.o
rm ../../Binaries/Linux/YGen
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG/Build/Linux[00m$ [?2004l
exit

Script done on 2025-10-22 12:40:32-03:00 [COMMAND_EXIT_CODE="0"]
