Script started on 2025-10-18 01:19:50-03:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="192" LINES="14"]
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG[00m$ python3 Scripts/Permutation_Generator.py
[?2004lObject count: 4
Permutation count: 16
{ 2, 3, 1, 0, },
{ 1, 0, 2, 3, },
{ 0, 3, 1, 2, },
{ 0, 2, 1, 3, },
{ 2, 0, 1, 3, },
{ 3, 1, 2, 0, },
{ 2, 0, 3, 1, },
{ 3, 2, 1, 0, },
{ 1, 2, 3, 0, },
{ 1, 0, 3, 2, },
{ 0, 3, 2, 1, },
{ 3, 0, 1, 2, },
{ 3, 2, 0, 1, },
{ 2, 1, 3, 0, },
{ 1, 3, 0, 2, },
{ 2, 1, 0, 3, },
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG[00m$ python3 Scripts/Permutation_Generator.py
[?2004lObject count: 8
Permutation count: 16
{ 6, 0, 7, 2, 1, 4, 3, 5, },
{ 3, 2, 4, 6, 0, 7, 5, 1, },
{ 1, 5, 0, 3, 6, 2, 7, 4, },
{ 0, 6, 2, 7, 3, 5, 4, 1, },
{ 2, 3, 7, 5, 0, 4, 6, 1, },
{ 2, 6, 5, 3, 0, 4, 1, 7, },
{ 2, 0, 1, 5, 3, 4, 7, 6, },
{ 2, 0, 1, 5, 4, 6, 7, 3, },
{ 5, 0, 1, 6, 3, 4, 7, 2, },
{ 5, 2, 7, 1, 3, 6, 0, 4, },
{ 3, 1, 7, 2, 5, 0, 6, 4, },
{ 3, 0, 5, 6, 1, 7, 2, 4, },
{ 2, 0, 5, 1, 6, 3, 7, 4, },
{ 1, 4, 7, 2, 6, 3, 5, 0, },
{ 3, 0, 5, 1, 7, 6, 4, 2, },
{ 6, 7, 5, 1, 0, 2, 4, 3, },
[?2004h]0;hp17cp@HP17CP: ~/Documents/Projects/Programming/YggdrasilPRNG[01;32mhp17cp@HP17CP[00m:[01;34m~/Documents/Projects/Programming/YggdrasilPRNG[00m$ [?2004l
exit

Script done on 2025-10-18 01:20:16-03:00 [COMMAND_EXIT_CODE="0"]
